'use client';

import {useEffect, useRef, useState} from 'react';
import {ArrowDownRight, ArrowUpRight, Bell, BellRing, Check, ChevronRight, CircleHelp, Headphones, Plus, RefreshCw, Settings2, ShoppingBag, Target, TrendingDown, Volume2, VolumeX, X, Pause, Play, Pencil, Trash2, Link2, ShieldCheck, Radio, PlugZap} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {newId,bestListing,effectivePrice,latest,makeDemo,money,recordSample,storeName,type Listing,type PriceAlert,type Store,type Watch} from '@/lib/watch';

const stamp = (s:string) => new Date(s).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const shortDate = (n:number) => new Date(n).toLocaleDateString('en-IN',{day:'numeric',month:'short'});

function Chart({watch}:{watch:Watch}) {
  const samples=watch.listings.flatMap(l=>l.samples), values=samples.map(s=>s.effective);
  if (!samples.length) return <div className="chart-empty"><TrendingDown/><p>Your first price starts the story.</p><span>Add a price or connect live checking to build history.</span></div>;
  const times=samples.map(s=>Date.parse(s.time)),start=Math.min(...times),end=Math.max(...times,start+1000),lo=Math.max(0,Math.min(...values,watch.target)*.87),hi=Math.max(...values,watch.target)*1.08;
  const x=(time:string)=>70+(Date.parse(time)-start)/(end-start)*620,y=(v:number)=>205-(v-lo)/(hi-lo)*170;
  return <div className="chart"><svg viewBox="0 0 750 250" role="img" aria-label={`Recorded estimated prices for ${watch.name}. Target ${money(watch.target)}.`}>
    {[0,1,2,3].map(n=>{const v=lo+(hi-lo)*n/3;return <g key={n}><line x1="70" x2="704" y1={y(v)} y2={y(v)} stroke="#e9edef"/><text x="0" y={y(v)+5} fill="#738088" fontSize="13">{money(Math.round(v/100)*100)}</text></g>})}
    <line x1="70" x2="704" y1={y(watch.target)} y2={y(watch.target)} stroke="#8d9b6d" strokeDasharray="5 5"/>
    <text x="703" y={y(watch.target)-8} fill="#607038" fontSize="13" textAnchor="end">Target {money(watch.target)}</text>
    {watch.listings.map(l=><g key={l.id}><polyline points={l.samples.map(s=>`${x(s.time)},${y(s.effective)}`).join(' ')} fill="none" stroke={l.store==='amazon'?'#1c343c':'#9cac44'} strokeWidth="3" strokeLinejoin="round"/>{l.samples.map((s,i)=><circle key={s.id} cx={x(s.time)} cy={y(s.effective)} r={i===l.samples.length-1?4:2} fill={l.store==='amazon'?'#1c343c':'#9cac44'}><title>{storeName(l.store)}: {money(s.effective)} · {stamp(s.time)} · {s.source}</title></circle>)}</g>)}
    <text x="70" y="240" fill="#738088" fontSize="13">{shortDate(start)}</text><text x="380" y="240" textAnchor="middle" fill="#738088" fontSize="13">{shortDate((start+end)/2)}</text><text x="704" y="240" textAnchor="end" fill="#738088" fontSize="13">{shortDate(end)}</text>
  </svg></div>;
}

export default function Dashboard(){
  const [watches,setWatches]=useState<Watch[]>([]),[demoWatches,setDemoWatches]=useState<Watch[]>([]),[demo,setDemo]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState('');
  const [selected,setSelected]=useState(''),[sound,setSound]=useState(false),[auto,setAuto]=useState(true),[busy,setBusy]=useState(false),[connectionOpen,setConnectionOpen]=useState(false),[keyDraft,setKeyDraft]=useState(''),[key,setKey]=useState(''),[serverKey,setServerKey]=useState(false),[notifications,setNotifications]=useState(false);
  const [editor,setEditor]=useState<Watch|null|undefined>(undefined),[recording,setRecording]=useState<Watch|null>(null),[deleting,setDeleting]=useState<Watch|null>(null);
  const audio=useRef<AudioContext|null>(null),seen=useRef(new Set<string>()),soundRef=useRef(false),notificationRef=useRef(false),refreshing=useRef(false),loadedRef=useRef(false);
  const list=demo?demoWatches:watches,active=list.find(w=>w.id===selected)||list[0],alerts=list.flatMap(w=>w.alerts).sort((a,b)=>b.time.localeCompare(a.time));
  const connected=!!key||serverKey;
  soundRef.current=sound; notificationRef.current=notifications;
  const activeLow=active?Math.min(...active.listings.flatMap(l=>[...Object.values(l.lows||{}),...l.samples.map(s=>s.effective)])):Infinity;
  const atTarget=list.filter(w=>{const b=bestListing(w);return b&&effectivePrice(latest(b)!.price,b)<=w.target}).length;
  const reduction=list.reduce((total,w)=>{const b=bestListing(w);if(!b)return total;const initial=Math.min(...w.listings.filter(l=>l.samples.length).map(l=>l.samples[0].effective));return total+Math.max(0,initial-effectivePrice(latest(b)!.price,b));},0);

  const contextState=useRef({list,demo});contextState.current={list,demo};
  useEffect(()=>{
    const context=(document as Document & {modelContext?:{registerTool:(tool:any,options:any)=>unknown}}).modelContext;
    if(!context?.registerTool)return;
    const lifetime=new AbortController();
    const register=(tool:any)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch{}};
    register({name:'read_watchlist',description:'Read products and latest observed prices in the currently visible watchlist. Demo values are illustrative.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:any)=>{if(!input||Object.keys(input).length)throw new Error('No arguments expected.');return {demo:contextState.current.demo,products:contextState.current.list.map(w=>({id:w.id,name:w.name,variant:w.variant,target:w.target,listings:w.listings.map(l=>({store:l.store,last:latest(l)||null}))}))};}});
    register({name:'show_price_history',description:'Select an existing product and show its price chart and offer breakdown. Does not change saved products.',inputSchema:{type:'object',properties:{productId:{type:'string'}},required:['productId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(!input||typeof input.productId!=='string'||Object.keys(input).some(k=>k!=='productId')||!contextState.current.list.some(w=>w.id===input.productId))throw new Error('Choose a product ID from read_watchlist.');setSelected(input.productId);await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);return {selectedProductId:input.productId};}});
    return()=>lifetime.abort();
  },[]);

  async function beep(force=false){
    if(!force&&!soundRef.current)return;
    try{
      audio.current??=new AudioContext();await audio.current.resume();
      if(audio.current.state!=='running')throw new Error('Sound is blocked.');
      const ctx=audio.current;
      [660,880,1100].forEach((freq,i)=>{const oscillator=ctx.createOscillator(),gain=ctx.createGain(),t=ctx.currentTime+i*.16;oscillator.type='sine';oscillator.frequency.value=freq;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.16,t+.02);gain.gain.exponentialRampToValueAtTime(.001,t+.22);oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start(t);oscillator.stop(t+.24);});
    }catch{setSound(false);toast.error('Sound is unavailable. Check your browser audio settings.');}
  }
  function announce(items:Watch[],initial=false){
    const incoming=items.flatMap(w=>w.alerts).filter(a=>!seen.current.has(a.id));
    items.flatMap(w=>w.alerts).forEach(a=>seen.current.add(a.id));
    if(initial||!incoming.length)return;
    void beep();
    for(const a of incoming.slice(0,3)){
      const title=`${a.source==='demo'?'Demo · ':a.source==='manual'?'Manual · ':''}${a.name}: ${money(a.price)}`;
      toast.success(title,{description:`${a.kind==='target'?'Target reached':'New recorded low'} on ${storeName(a.store)}`,duration:7000});
      if(notificationRef.current&&'Notification'in window&&Notification.permission==='granted'){try{new Notification(title,{body:`${a.kind==='target'?'Target reached':'New recorded low'} on ${storeName(a.store)}`,tag:a.id});}catch{}}
    }
  }
  async function load(){
    try{const r=await fetch('/api/watchlist',{cache:'no-store'});const d=await r.json() as {error?:string;watches:Watch[];configured?:boolean;message?:string};if(!r.ok)throw new Error(d.error||'Could not load your watchlist.');setWatches(d.watches);setServerKey(!!d.configured);announce(d.watches,true);if(!loadedRef.current)setDemo(!d.watches.length);setError('');loadedRef.current=true;}catch(e){setError((e as Error).message);if(!loadedRef.current)setDemo(true);}finally{setLoaded(true);}
  }
  useEffect(()=>{setDemoWatches(makeDemo());void load();return()=>{void audio.current?.close();};},[]);
  async function command(action:string,data:Record<string,unknown>={}){
    setBusy(true);
    try{const r=await fetch('/api/watchlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const d=await r.json() as {error?:string;watches:Watch[];configured?:boolean;message?:string};if(!r.ok)throw new Error(d.error||'Could not save. Please try again.');setWatches(d.watches);announce(d.watches);setError('');return d;}catch(e){toast.error((e as Error).message);throw e;}finally{setBusy(false);}
  }
  async function refresh(manual=true){
    if(refreshing.current)return;
    if(demo){toast.info('Demo prices are examples. Use “Simulate a drop” to try an alert.');return;}
    if(!connected){setConnectionOpen(true);return;}
    refreshing.current=true;
    try{const d=await command('refresh',{apiKey:key});if(manual)toast(d.message||'Prices checked.');}catch{}finally{refreshing.current=false;}
  }
  useEffect(()=>{
    if(demo||!auto||!connected)return;
    const interval=setInterval(()=>{if(document.visibilityState==='visible')void refresh(false);},300000);
    return()=>clearInterval(interval);
  },[demo,auto,key,serverKey]);
  useEffect(()=>{const resume=()=>{if(document.visibilityState==='visible'&&auto&&connected&&!demo)void refresh(false)};document.addEventListener('visibilitychange',resume);return()=>document.removeEventListener('visibilitychange',resume)},[auto,connected,demo,key]);
  async function enableSound(){if(sound){setSound(false);return;}await beep(true);if(audio.current?.state==='running'){setSound(true);toast.success('Sound enabled for this tab.');}}
  function simulate(){
    if(!active)return;
    const l=bestListing(active)!;const price=Math.max(100,Math.min(latest(l)!.price-500,active.target-100+(l.coupon+l.bank)));
    const updated=recordSample(active,l.id,{id:newId(),time:new Date().toISOString(),price,effective:effectivePrice(price,l),source:'demo'});
    const items=demoWatches.map(w=>w.id===active.id?updated:w);setDemoWatches(items);announce(items);if(!sound)toast.info('Enable sound to hear the alert.');
  }
  async function pause(w:Watch){if(demo){setDemoWatches(items=>items.map(i=>i.id===w.id?{...i,paused:!i.paused}:i));return;}try{await command('pause',{id:w.id,revision:w.revision,paused:!w.paused});}catch{}}
  return <>
    <Toaster position="bottom-right" theme="light" richColors/>
    <header className="topbar"><a className="wordmark" href="/" aria-label="Dropwatch home"><span className="brand-symbol"><ArrowDownRight size={23}/></span>dropwatch<span className="brand-dot">.</span></a><div className="nav-label"><span/>YOUR SALE WATCHLIST</div><div className="top-right"><span className="private-label"><ShieldCheck size={15}/> Private workspace</span><button className="avatar" title="Your private watchlist" onClick={()=>toast.info('This watchlist is private to your signed-in account.')}>Y</button></div></header>
    <main className="workspace">
      <div className="page-title"><div><div className="eyebrow">BUY AT YOUR PRICE</div><h1>Your watchlist<span>.</span></h1><p>A little patience. A better price.</p></div><button className="button primary" onClick={()=>setEditor(null)}><Plus size={18}/> Add a product</button></div>
      <div className="connection-bar"><div><span className={`status-indicator ${connected&&!demo?'ready':''}`}/><strong>{demo?'Demo mode':connected?'Price connection ready':'Live prices not connected'}</strong><span className="bar-detail">{demo?'Illustrative prices. Try a drop to see your alert.':connected?'Checks run while this tab is open and active.':'Save your products now, then connect a price source.'}</span></div><button onClick={()=>demo?setDemo(false):setConnectionOpen(true)}>{demo?'Open my watchlist':connected?'Manage connection':'Connect live prices'}<ArrowUpRight size={16}/></button></div>
      {error&&<div className="error-banner" role="alert">{error} <button onClick={()=>void load()}>Try again</button></div>}
      <section className="summary" aria-label="Watchlist overview"><div className="summary-cell"><span>Products on your radar <ShoppingBag size={17}/></span><strong>{String(list.length).padStart(2,'0')}<small>{demo?'demo products':'saved products'}</small></strong></div><div className="summary-cell"><span>At your target <Target size={17}/></span><strong>{String(atTarget).padStart(2,'0')}<small>{atTarget?'worth a closer look':'waiting for the drop'}</small></strong></div><div className="summary-cell"><span>Drop since first recorded price <TrendingDown size={18}/></span><strong className="saving">{money(reduction)}<small>{demo?'illustrative savings':'across your watchlist'}</small></strong></div></section>
      <div className="content-grid"><div className="main-column"><section className="watch-section"><div className="section-heading"><h2>{demo?'Example watchlist':'Watching'} <span>{list.length}</span></h2><div className="toolbar">{!demo&&<button className="text-button" onClick={()=>setDemo(true)}>Try demo</button>}<button className="icon-text" onClick={()=>void refresh()} disabled={busy||!list.length}><RefreshCw size={15} className={busy?'spin':''}/>{busy?'Checking…':'Check prices'}</button></div></div>
      {!loaded?<div className="empty-state" role="status">Loading your watchlist…</div>:list.length===0?<div className="empty-state"><div className="empty-icon"><ShoppingBag size={30}/></div><h3>Your next good deal starts here.</h3><p>Add the exact model, size or colour you want and set your price.</p><button className="button primary" onClick={()=>setEditor(null)}><Plus size={17}/> Add your first product</button></div>:<div className="product-grid">{list.map(w=>{const b=bestListing(w),last=b&&latest(b),price=last&&effectivePrice(last.price,b!),met=price!==undefined&&price<=w.target;return <article className={`product-card ${active?.id===w.id?'selected':''}`} key={w.id}>
      <div className="product-top"><span className={`product-icon ${w.name.toLowerCase().includes('airpod')?'audio-icon':''}`}>{w.name.toLowerCase().includes('airpod')?<Headphones size={27}/>:<ShoppingBag size={27}/>}</span><span className={`pill ${met?'green':''}`}>{w.paused?'Paused':met?'Target reached':last?.source==='live'?'Price received':demo?'Demo':'Manual / awaiting data'}</span><button className="mini-icon" aria-label={`Edit ${w.name}`} onClick={()=>setEditor(w)}><Pencil size={15}/></button></div>
      <button className="product-name" onClick={()=>setSelected(w.id)}><h3>{w.name}</h3><p>{w.variant}</p></button>
      <div className="product-price"><span>Best estimated price</span><strong>{money(price)}{met&&<span className="price-check"><Check size={17}/></span>}</strong>{last?<small>{storeName(b!.store)} · {demo?'sample price':`${last.source} · ${stamp(last.time)}`}</small>:<small>Waiting for a recorded price</small>}</div>
      <div className="store-prices">{w.listings.map(l=><div key={l.id}><span className={`store-icon ${l.store}`}>{l.store==='amazon'?'a':'f'}</span><span>{storeName(l.store)}</span><strong>{latest(l)?money(effectivePrice(latest(l)!.price,l)):'—'}</strong></div>)}</div>
      <div className="target-row"><span><Target size={14}/> Target <b>{money(w.target)}</b></span><button onClick={()=>setSelected(w.id)} aria-label={`Show price history for ${w.name}`} className="text-button">History <ChevronRight size={15}/></button></div>
      </article>})}</div>}
      </section>
      {active&&<section className="panel history-panel"><div className="section-heading"><div><h2>Price history</h2><p>{active.name} <span>· {demo?'Sample data':'Last 500 observations per store'}</span></p></div><span className="period-tag">Lowest recorded <b>{Number.isFinite(activeLow)?money(activeLow):'—'}</b></span></div><div className="chart-key"><span><i/> Amazon</span><span><i className="flipkart-line"/> Flipkart</span><span className="chart-metric">Estimated payable price</span></div><Chart watch={active}/><div className="history-footer"><span><CircleHelp size={15}/> A recorded low is the lowest seen here, not a prediction.</span>{demo?<button className="text-button" onClick={simulate}><TrendingDown size={15}/> Simulate a drop</button>:<button className="text-button" onClick={()=>setRecording(active)}>Record a price <Plus size={15}/></button>}</div></section>}
      {active&&<section className="panel breakdown-panel"><div className="section-heading"><h2>The price you could pay</h2><button className="text-button" onClick={()=>setEditor(active)}>Edit offers <Pencil size={14}/></button></div><div className="offer-grid">{active.listings.map(l=>{const sample=latest(l),valid=Date.parse(l.offersUntil)>Date.now();return <div className="offer-card" key={l.id}><div className="offer-title"><strong><span className={`store-icon ${l.store}`}>{l.store==='amazon'?'a':'f'}</span>{storeName(l.store)}</strong>{l.url&&<a href={l.url} target="_blank" rel="noopener noreferrer">Open product <ArrowUpRight size={14}/></a>}</div><dl><div><dt>Listed price</dt><dd>{money(sample?.price)}</dd></div><div><dt>Your coupon</dt><dd className="discount">−{money(valid?l.coupon:0)}</dd></div><div><dt>Your instant bank discount</dt><dd className="discount">−{money(valid?l.bank:0)}</dd></div><div><dt>Delivery / fees you entered</dt><dd>+{money(l.shipping)}</dd></div><div className="offer-total"><dt>Estimated total</dt><dd>{sample?money(effectivePrice(sample.price,l)):'—'}</dd></div></dl>{l.error&&<p className="listing-error">{l.error}</p>}{(l.coupon>0||l.bank>0)&&<p className="offer-note">{valid?`Entered offers expire ${stamp(l.offersUntil)}`:'Entered offers expired; discounts excluded.'}</p>}</div>})}</div><p className="fineprint">Offers and delivery costs are entered by you. Confirm eligibility, offer stacking, stock and the final price at checkout. Cashback and exchange values are excluded.</p></section>}
      </div>
      <aside className="side-column"><section className="alert-panel"><div className="alert-heading"><span className="bell-icon"><BellRing size={23}/></span><div><h2>Catch the drop.</h2><p>Let the right price find you.</p></div></div><div className="control-row"><div><strong>Sound alerts</strong><span>{sound?'Sound is on for this tab':'Enable once in this tab'}</span></div><Switch aria-label="Enable sound alerts" checked={sound} onCheckedChange={()=>void enableSound()}/></div><button className="test-sound" onClick={()=>void beep(true)}><Volume2 size={17}/> Test the beep <Play size={13}/></button><div className="control-row auto-row"><div><strong>Auto-check prices</strong><span>Every 5 min when connected</span></div><Switch aria-label="Automatically check every five minutes" checked={auto} onCheckedChange={setAuto}/></div><p className="alert-explainer">Keep this tab open and your device awake. Background tabs may be delayed; a closed tab cannot monitor or beep.</p><button className="notification-button" disabled={notifications} onClick={async()=>{if(!('Notification'in window)){toast.info('This browser does not support desktop notifications.');return;}try{const granted=await Notification.requestPermission();setNotifications(granted==='granted');toast(granted==='granted'?'Notifications enabled while this tab is running.':'Notification permission was not granted.');}catch{toast.error('Notifications are unavailable in this browser.');}}}><Bell size={15}/>{notifications?'Notifications enabled':'Enable desktop notifications'}</button></section>
      <section className="panel activity-panel"><div className="section-heading"><h2>Recent alerts</h2><span className="count">{alerts.length}</span></div>{alerts.length?<div className="activity-list" aria-live="polite">{alerts.slice(0,6).map(a=><div className="activity" key={a.id}><span className="activity-icon"><ArrowDownRight size={18}/></span><div><strong>{a.name}</strong><p>{money(a.price)} · {a.kind==='target'?'Target reached':'New recorded low'}</p><small>{a.source==='demo'?'Demo':a.source==='manual'?'Manual entry':'Live price'} · {stamp(a.time)}</small></div></div>)}</div>:<div className="no-alerts"><Bell size={25}/><p>Quiet for now.</p><span>Your price alerts will appear here.</span>{demo&&<button className="text-button" onClick={simulate}>Try a sample price drop <ChevronRight size={14}/></button>}</div>}</section>
      {active&&<section className="watch-settings"><div><span className="eyebrow">SELECTED PRODUCT</span><h3>{active.name}</h3></div><div className="setting-detail"><span>Alert me when</span><strong>{active.rule==='both'?'Target or new low':active.rule==='target'?'Target is reached':'A new low is recorded'}</strong></div><div className="settings-actions"><button onClick={()=>void pause(active)}>{active.paused?<Play size={15}/>:<Pause size={15}/>} {active.paused?'Resume':'Pause'} alerts</button><button onClick={()=>setDeleting(active)} aria-label={`Remove ${active.name}`}><Trash2 size={15}/></button></div></section>}
      <div className="retailer-note"><ShoppingBag size={17}/><p>Built for Amazon India & Flipkart.<br/>Sale dates follow retailer announcements.</p></div>
      </aside></div>
      <footer><span className="footer-brand">dropwatch.</span><span>Good things come to those who watch.</span><button onClick={()=>setConnectionOpen(true)}><PlugZap size={14}/>{connected?'Connection settings':'Connect your price source'}</button></footer>
    </main>
    <ProductEditor value={editor} onClose={()=>setEditor(undefined)} busy={busy} onSave={async(data)=>{if(editor&&demo){const updated={...editor,...data,listings:editor.listings.map(l=>({...l,...data.listings.find((n:any)=>n.store===l.store)}))} as Watch;setDemoWatches(items=>items.map(w=>w.id===updated.id?updated:w));setEditor(undefined);toast.success('Demo updated.');return;}try{await command(editor?'edit':'create',{data,id:editor?.id,revision:editor?.revision});setEditor(undefined);setDemo(false);toast.success(editor?'Product updated.':'Product added to your watchlist.');}catch{}}}/>
    <Dialog open={connectionOpen} onOpenChange={setConnectionOpen}><DialogContent><DialogHeader><DialogTitle>Connect live prices</DialogTitle><DialogDescription>Use your Scrapingdog account to check Amazon India and Flipkart product prices.</DialogDescription></DialogHeader><div className="connection-info"><PlugZap size={22}/><p>{serverKey?'A price provider is configured for this site.':key?'A key is added for this tab. Check your products to verify it.':'Live checking needs your own provider API key. Your watchlist works with manual prices in the meantime.'}</p></div><form onSubmit={e=>{e.preventDefault();setKey(keyDraft.trim());setKeyDraft('');setDemo(false);setConnectionOpen(false);toast.success('Key added for this tab. Click Check prices to verify the connection.');}}><label className="field">Scrapingdog API key<input type="password" autoComplete="off" value={keyDraft} onChange={e=>setKeyDraft(e.target.value)} placeholder="Paste your API key" minLength={10} maxLength={256} required/></label><p className="fineprint">The key stays in this tab’s memory and is sent securely to the server for price checks. It is not saved to your watchlist. Checks use your provider credits.</p><button className="button primary full" type="submit">Use this key <ArrowUpRight size={16}/></button></form>{key&&<button className="text-button" onClick={()=>{setKey('');toast.success('Key removed from this tab.');}}>Disconnect this tab</button>}<a className="documentation-link" href="https://www.scrapingdog.com/documentation/flipkart-product-api/" target="_blank" rel="noopener noreferrer">Provider documentation & account setup <ArrowUpRight size={15}/></a><p className="fineprint">Checks run every 5 minutes while this page is active. This version does not run checks with the browser closed. Product prices can differ by delivery location; verify the retailer checkout.</p></DialogContent></Dialog>
    <RecordPrice watch={recording} busy={busy} onClose={()=>setRecording(null)} onSave={async(listingId,price)=>{if(!recording)return;try{await command('record',{id:recording.id,revision:recording.revision,listingId,price});setRecording(null);toast.success('Manual price recorded.');}catch{}}}/>
    <AlertDialog open={!!deleting} onOpenChange={open=>!open&&setDeleting(null)}><AlertDialogContent><AlertDialogTitle>Remove {deleting?.name}?</AlertDialogTitle><AlertDialogDescription>This removes this product and its recorded history from your watchlist.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep product</AlertDialogCancel><AlertDialogAction onClick={async()=>{if(!deleting)return;if(demo)setDemoWatches(items=>items.filter(w=>w.id!==deleting.id));else try{await command('remove',{id:deleting.id,revision:deleting.revision});}catch{}setDeleting(null);}}>Remove product</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>;
}

function ProductEditor({value,onClose,onSave,busy}:{value:Watch|null|undefined;onClose:()=>void;onSave:(data:any)=>Promise<void>;busy:boolean}){
  const [rule,setRule]=useState('both');
  useEffect(()=>setRule(value?.rule||'both'),[value]);
  return <Dialog open={value!==undefined} onOpenChange={v=>!v&&onClose()}><DialogContent className="product-dialog"><DialogHeader><DialogTitle>{value?'Edit your product':'Add to your watchlist'}</DialogTitle><DialogDescription>Use links for the same exact model, size and colour on both stores.</DialogDescription></DialogHeader><form key={value?.id||'new'} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),num=(k:string)=>Number(f.get(k)||0);const listings=(['amazon','flipkart']as Store[]).map(store=>({store,url:String(f.get(`${store}-url`)||'').trim(),coupon:num(`${store}-coupon`),bank:num(`${store}-bank`),shipping:num(`${store}-shipping`),offersUntil:f.get(`${store}-expiry`)?new Date(String(f.get(`${store}-expiry`))).toISOString():'',initialPrice:num(`${store}-price`)})).filter(l=>l.url||value?.id.startsWith('demo'));if(!listings.length){toast.error('Add at least one Amazon or Flipkart product link.');return;}if(listings.some(l=>(l.coupon||l.bank)&&!l.offersUntil)){toast.error('Set an expiry for each coupon or bank discount.');return;}await onSave({name:String(f.get('name')),variant:String(f.get('variant')),target:num('target'),rule,listings});}}>
    <label className="field">Product name<input name="name" required maxLength={120} defaultValue={value?.name} placeholder="e.g. Nike Pegasus 41"/></label><label className="field">Exact variant<input name="variant" required maxLength={180} defaultValue={value?.variant} placeholder="e.g. Men · UK 9 · Black / White"/></label><div className="form-two"><label className="field">Target price (₹)<input type="number" name="target" min="1" max="10000000" step="0.01" required defaultValue={value?.target} placeholder="7000"/></label><label className="field">Alert condition<Select value={rule} onValueChange={setRule}><SelectTrigger className="select-field"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="both">Target or new low</SelectItem><SelectItem value="target">Target reached</SelectItem><SelectItem value="low">New recorded low</SelectItem></SelectContent></Select></label></div>
    {(['amazon','flipkart'] as Store[]).map(store=>{const l=value?.listings.find(l=>l.store===store);return <fieldset className="retailer-form" key={store}><legend><span className={`store-icon ${store}`}>{store==='amazon'?'a':'f'}</span>{storeName(store)}</legend><label className="field">Product URL<input name={`${store}-url`} type="url" maxLength={2000} defaultValue={l?.url} placeholder={store==='amazon'?'https://www.amazon.in/dp/…':'https://www.flipkart.com/…/p/…?pid=…'}/></label><p className="input-hint">Paste the full product link after selecting your variant. Short links are not supported.</p>{!l&&<label className="field">Current listed price (₹, optional)<input type="number" name={`${store}-price`} min="1" max="10000000" step="0.01" placeholder="Enter manually, or wait for live data"/></label>}<details><summary>Your eligible offers & delivery costs</summary><div className="form-three">{(['coupon','bank','shipping'] as const).map(k=><label className="field" key={k}>{k==='coupon'?'Coupon (₹)':k==='bank'?'Bank discount (₹)':'Fees (₹)'}<input type="number" name={`${store}-${k}`} min="0" max="10000000" step="0.01" defaultValue={l?.[k]||0}/></label>)}</div><label className="field">Coupon / bank offer expiry<input name={`${store}-expiry`} type="datetime-local" defaultValue={l?.offersUntil?new Date(Date.parse(l.offersUntil)-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):''}/></label><p className="input-hint">Only include instant discounts you qualify for and can combine. Expired discounts are excluded.</p></details></fieldset>})}<button type="submit" className="button primary full" disabled={busy}>{busy?'Saving…':value?'Save changes':'Add product'}<Check size={17}/></button></form></DialogContent></Dialog>;
}
function RecordPrice({watch,onClose,onSave,busy}:{watch:Watch|null;onClose:()=>void;onSave:(id:string,price:number)=>Promise<void>;busy:boolean}){
  const [id,setId]=useState('');useEffect(()=>setId(watch?.listings[0]?.id||''),[watch]);
  return <Dialog open={!!watch} onOpenChange={v=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>Record a price</DialogTitle><DialogDescription>{watch?.name} · Save the listed price you see on the store. Your eligible offers are applied separately.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();await onSave(id,Number(new FormData(e.currentTarget).get('price')));}}><label className="field">Store<Select value={id} onValueChange={setId}><SelectTrigger className="select-field"><SelectValue/></SelectTrigger><SelectContent>{watch?.listings.map(l=><SelectItem key={l.id} value={l.id}>{storeName(l.store)}</SelectItem>)}</SelectContent></Select></label><label className="field">Listed price (₹)<input name="price" type="number" min="1" max="10000000" step="0.01" required/></label><p className="fineprint">Saved as a manual observation, with the current time.</p><button className="button primary full" disabled={busy}>{busy?'Saving…':'Save price'}</button></form></DialogContent></Dialog>;
}
